# Generated by Django 4.0 on 2023-04-13 08:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0002_alter_movie_name_alter_movie_protagonists_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='movie',
            name='ranking',
            field=models.IntegerField(default=0, verbose_name='Ranking'),
        ),
        migrations.AlterField(
            model_name='movie',
            name='start_date',
            field=models.DateTimeField(),
        ),
    ]
